services:
  db:
    image: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/pg_data
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    environment:
      BOT_TOKEN: ""
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: password
      DATABASE_HOST: postgres
      DATABASE_NAME: postgres